### ISSUE TITLE
Kumiko, The Treasure Hunter (2014)

### ISSUE THREAD

**Issue by chapmanjacobd** [Enoch2090/Fargo#1]
Hey Yucheng,

Thanks for star-ing my [hn_mining](https://github.com/chapmanjacobd/hn_mining#readme) repo. I don't know if you noticed my other project, [library](https://github.com/chapmanjacobd/lb/), which is similar to this. You might be interested to check it out

It doesn't have any [find](https://github.com/Enoch2090/Fargo/blob/main/fargo/commands/find.py) functionality but some other features are arguably more sophisticated.

For example, instead of [asking](https://github.com/Enoch2090/Fargo/blob/5f9eb714e54e7971dde006c7f6f23d32535e25de/fargo/commands/watch.py#L43) if you are done watching, I assume you are done watching if mpv (or the configured player) is closed with exit 0. If you close mpv with ctrl-c then the exit code 4 will bubble up and I'll assume you are not finished watching something and it won't be marked as watched. I'm not sure how intuitive this is so I explained that here in this paragraph

Please feel free to leave this issue open or close it at any time

**Comment by Enoch2090** [comment]
Hi Jakob:
Thanks for the advice! Another option I was thinking of is to check whether the UNIX file descriptor is still open, so the program knows when you quit watching, and then compare the time with the length of the media. But your solution is definetely a very practival one. I haven't used Fargo for a while, but I think sometimes in the future I will refactor it out of interest (see [Nyquisis](https://github.com/Enoch2090/Nyquisis), I did such refactor once). I will try to implement this idea.
Again, thanks for tha advice! I starred [hn-mining](https://github.com/chapmanjacobd/hn_mining#readme) because I am working on a GitHub mining project, your projects has been a real source of inspiration.
